name: Build

on:
  workflow_dispatch:
  release:
    types: [ released ]
  
  push:
    branches:
      - 'main'

jobs:
  
  SetupBuildInfo:
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.SetupBuildInfo.outputs.build-id }}
      build-version: ${{ steps.SetupBuildInfo.outputs.build-version }}
      build-timestamp: ${{ steps.SetupBuildInfo.outputs.build-timestamp }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: SetupBuildInfo
        id: SetupBuildInfo
        run: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
  
  PackHostingExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: PackHostingExtensions
        id: PackHostingExtensions
        run: dotnet run --project _atom/_atom.csproj PackHostingExtensions --skip --headless
      
      - name: Upload DecSm.Extensions.Hosting
        uses: actions/upload-artifact@v4
        with:
          name: DecSm.Extensions.Hosting
          path: "${{ github.workspace }}/.github/publish/DecSm.Extensions.Hosting"
  
  TestHostingExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: TestHostingExtensions
        id: TestHostingExtensions
        run: dotnet run --project _atom/_atom.csproj TestHostingExtensions --skip --headless
      
      - name: Upload DecSm.Extensions.Hosting.Tests
        uses: actions/upload-artifact@v4
        with:
          name: DecSm.Extensions.Hosting.Tests
          path: "${{ github.workspace }}/.github/publish/DecSm.Extensions.Hosting.Tests"
  
  PushToNuget:
    needs: [ PackHostingExtensions ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Download DecSm.Extensions.Hosting
        uses: actions/download-artifact@v4
        with:
          name: DecSm.Extensions.Hosting
          path: "${{ github.workspace }}/.github/artifacts/DecSm.Extensions.Hosting"
      
      - name: PushToNuget
        id: PushToNuget
        run: dotnet run --project _atom/_atom.csproj PushToNuget --skip --headless
        env:
          nuget-push-api-key: ${{ secrets.NUGET_PUSH_API_KEY }}
  
  PushToRelease:
    needs: [ PackHostingExtensions ]
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Download DecSm.Extensions.Hosting
        uses: actions/download-artifact@v4
        with:
          name: DecSm.Extensions.Hosting
          path: "${{ github.workspace }}/.github/artifacts/DecSm.Extensions.Hosting"
      
      - name: PushToRelease
        id: PushToRelease
        run: dotnet run --project _atom/_atom.csproj PushToRelease --skip --headless
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
