name: Validate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  
  SetupBuildInfo:
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.SetupBuildInfo.outputs.build-id }}
      build-version: ${{ steps.SetupBuildInfo.outputs.build-version }}
      build-timestamp: ${{ steps.SetupBuildInfo.outputs.build-timestamp }}
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: SetupBuildInfo
        id: SetupBuildInfo
        run: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
  
  PackHostingExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: PackHostingExtensions
        id: PackHostingExtensions
        run: dotnet run --project _atom/_atom.csproj PackHostingExtensions --skip --headless
  
  TestHostingExtensions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: TestHostingExtensions
        id: TestHostingExtensions
        run: dotnet run --project _atom/_atom.csproj TestHostingExtensions --skip --headless
      
      - name: Upload DecSm.Extensions.Hosting.Tests
        uses: actions/upload-artifact@v4
        with:
          name: DecSm.Extensions.Hosting.Tests
          path: "${{ github.workspace }}/.github/publish/DecSm.Extensions.Hosting.Tests"
